---
- name: "Cron Audit CIS"
  hosts: all
  tasks:
    - name: Remove file (delete file)
      file:
        path: /etc/cron.deny
        state: absent

    - name: Removing /etc/cron.deny
       file:
        path: /etc/at.deny
        state: absent

    - name: Removing /etc/at.deny
      file:
        path: /etc/at.deny
        state: absent
      
    - name: Check if /etc/cron.allow is present
      stat:
        path: /etc/cron.allow
      register: crEx

    - name: Creating /etc/cron.allow
      file: 
        path: /etc/cron.allow
        state: touch
        mode: 0600
        owner: root
        group: root
      when: crEx == false

    - name: Check if /etc/at.allow is present
      stat:
        path: /etc/at.allow
      register: atEx

    - name: Creating /etc/at.allow
      file:
        path: /etc/at.allow
        state: touch
        mode: 0600
        owner: root
        group: root
      when: atEx == false 