---
- name: Configure umask
  hosts: all
  become: true
  tasks:
    - name:  modify the umask
      command: grep -RPi '(^|^[^#])\s*umask\s+([0-7][0-7][01][0-7]\b|[0-7][0-7][0-7][0-6]\b|[0-7][01][0-7]\b|[0-7][0-7][0-6]\b|(u=[rwx]{0,3},)?(g=[rwx]{0,3},)?o=[rwx]+\b|(u=[rwx]{1,3},)?g=[^rx]{1,3}(,o=[rwx]{0,3})?\b)' /etc/bashrc /etc/profile /etc/profile.d/.sh
    - name: Edit /etc/login.defs
      lineinfile:
        path: /etc/login.defs
        line: "UMASK 027"
        state: present